# Generated by Django 2.2.6 on 2020-05-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='description',
            field=models.TextField(default='Made in the far galaxy of Obalende with a specified turbo speed of 500km/h. Can reach far galaxies in the blink of an eye.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suit',
            name='description',
            field=models.TextField(default='Made in the far galaxy of Obalende with a specified turbo speed of 500km/h. Can reach far galaxies in the blink of an eye.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suit',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
