# Generated by Django 2.2.6 on 2020-05-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixr', '0005_auto_20200510_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='user',
            new_name='userme',
        ),
    ]
