# Generated by Django 2.2.6 on 2020-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixr', '0007_auto_20200510_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
