# Generated by Django 2.2.6 on 2020-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixr', '0008_customerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_ref_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
